"""Registro ACTIONS — ordem de execução (CLAUDE.md §3.4)."""

from __future__ import annotations

from src.pipeline.actions import (
    action_01_ingest,
    action_02_extract,
    action_03_quality,
    action_04_methodology,
    action_05_regulatory,
    action_06_codegen,
    action_07_stability,
    action_08_backtest,
    action_09_extended,
    action_10_report,
)
from src.pipeline.contracts import ActionSpec

ACTIONS: dict[str, ActionSpec] = {
    "01_ingest_documentation": ActionSpec(
        id="01_ingest_documentation",
        name="Ingestão de documentação",
        depends_on=[],
        input_schema={"doc_paths": "list[str]"},
        output_schema={"methodological_text": "str", "documents": "list[dict]", "has_code_example": "bool"},
        prompt_templates=[],
        run=action_01_ingest.run,
    ),
    "02_extract_model_spec": ActionSpec(
        id="02_extract_model_spec",
        name="Extração da especificação do modelo",
        depends_on=["01_ingest_documentation"],
        input_schema={"methodological_text": "str"},
        output_schema={"metrics": "list[dict]"},
        prompt_templates=["02_extract_model_spec/extract.md"],
        run=action_02_extract.run,
    ),
    "03_assess_doc_quality": ActionSpec(
        id="03_assess_doc_quality",
        name="Avaliação da qualidade da documentação",
        depends_on=["02_extract_model_spec"],
        input_schema={"methodological_text": "str"},
        output_schema={"itens": "list[dict]", "nota_agregada": "float"},
        prompt_templates=["03_assess_doc_quality/rubric.md"],
        run=action_03_quality.run,
    ),
    "04_assess_methodology": ActionSpec(
        id="04_assess_methodology",
        name="Avaliação da qualidade metodológica",
        depends_on=["02_extract_model_spec"],
        input_schema={"metrics": "list[dict]"},
        output_schema={"hipoteses_avaliadas": "list[dict]", "referencias_citadas": "list[dict]"},
        prompt_templates=["04_assess_methodology/methodology.md"],
        run=action_04_methodology.run,
    ),
    "05_regulatory_adherence": ActionSpec(
        id="05_regulatory_adherence",
        name="Aderência normativa (condicional)",
        depends_on=["02_extract_model_spec"],
        input_schema={"metrics": "list[dict]", "norm_text": "str | None"},
        output_schema={"clausulas": "list[dict]"},
        prompt_templates=[],
        run=action_05_regulatory.run,
    ),
    "06_generate_reference_code": ActionSpec(
        id="06_generate_reference_code",
        name="Geração de código de referência",
        depends_on=["02_extract_model_spec"],
        input_schema={"metrics": "list[dict]"},
        output_schema={"modules": "list[dict]"},
        prompt_templates=[],
        run=action_06_codegen.run,
    ),
    "07_stability_tests": ActionSpec(
        id="07_stability_tests",
        name="Testes de estabilidade",
        depends_on=["06_generate_reference_code"],
        input_schema={"modules": "list[dict]"},
        output_schema={"elasticidade": "list[dict]"},
        prompt_templates=[],
        run=action_07_stability.run,
    ),
    "08_backtesting": ActionSpec(
        id="08_backtesting",
        name="Backtesting / performance",
        depends_on=["06_generate_reference_code"],
        input_schema={"modules": "list[dict]"},
        output_schema={"holding_periods": "list[dict]"},
        prompt_templates=[],
        run=action_08_backtest.run,
    ),
    "09_extended_test_suite": ActionSpec(
        id="09_extended_test_suite",
        name="Esteira de testes extensível",
        depends_on=["06_generate_reference_code"],
        input_schema={},
        output_schema={"executados": "list[dict]", "pendentes": "list[dict]"},
        prompt_templates=[],
        run=action_09_extended.run,
    ),
    "10_replicability_report": ActionSpec(
        id="10_replicability_report",
        name="Replicabilidade",
        depends_on=[
            "03_assess_doc_quality",
            "04_assess_methodology",
            "05_regulatory_adherence",
            "06_generate_reference_code",
            "07_stability_tests",
            "08_backtesting",
            "09_extended_test_suite",
        ],
        input_schema={},
        output_schema={"report_path": "str"},
        prompt_templates=[],
        run=action_10_report.run,
        always_run=True,
    ),
}
